# /docker-compose.yml (Definitive, Corrected Command Version)

services:
  nginx:
    image: nginx:latest
    container_name: corpus_nginx
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: ./server
    container_name: corpus_web_app
    env_file: .env
    volumes:
      - ./server:/app
      - corpus_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "flask init-db && 
             gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 120 'app:create_app()'"

  worker:
    build: ./server
    container_name: corpus_worker
    env_file: .env
    volumes:
      - ./server:/app
      - corpus_uploads:/app/uploads
    depends_on:
      - redis
      - db
      - tika
      - chroma
      - ollama
    # --- THIS IS THE FIX ---
    # The comment has been removed. The command now starts correctly with "sh -c".
    command: >
      sh -c "echo 'Worker waiting for services...' &&
             sleep 30 &&
             echo 'Worker starting...' &&
             celery -A celery_worker.celery worker --loglevel=info"
    # --- END OF FIX ---

  redis:
    image: redis:7-alpine
    container_name: corpus_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tika:
    image: apache/tika:latest-full
    container_name: corpus_tika
    ports: ["9998:9998"]

  db:
    image: postgres:15
    container_name: corpus_db
    env_file: .env
    volumes:
      - corpus_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chromadb/chroma
    container_name: corpus_chroma
    ports: ["8000:8000"]
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=TRUE

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: corpus_ollama
    ports: ["11434:11434"]
    volumes:
      - ollama_data:/root/.ollama

volumes:
  corpus_data:
  chroma_data:
  ollama_data:
  corpus_uploads: