# /docker-compose.yml (Corrected Version)

services:
  nginx:
    image: nginx:latest
    container_name: corpus_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web

  web:
    build: ./server
    container_name: corpus_web_app
    env_file: .env
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
      tika:
        condition: service_healthy
    expose:
      - "5000"

    tika:
    # This tells Docker to build our custom image using the new file
    build:
      context: .
      dockerfile: tika.Dockerfile
    container_name: corpus_tika
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
      
  db:
    image: postgres:15
    container_name: corpus_db
    env_file: .env
    volumes:
      - corpus_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # --- CORRECTED FORMAT ---
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      # --- END CORRECTION ---

volumes:
  corpus_data: